### ISSUE TITLE
Add a GIT-based version of the tool in the output and generated ontologies.

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/owl-adapter#22]
## User Story
As a **dev/ops**, I would like **the output of the `oml-adapter` to include a GIT-based version in the output and in the generated ontologies (as annotation) * so that **reporting problems w.r.t. a specific version of the tool becomes easier.**.

## Detailed Description
Description providing additional details and context.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

## Sub-task List
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by melaasar** [comment]
You can see the version of the used tools when you run gradle with `--debug` flag. If this does not address the issue, please reopen and elaborate.
