### ISSUE TITLE
Support for SWRL constructs

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/owl-adapter#23]
## User Story
As a **caesar user**, I would like **support for OML extended w/ SWRL constructs per https://github.com/opencaesar/oml/issues/27** so that **I can map OML to OWL.**.

## Detailed Description
Description providing additional details and context.

See: https://github.com/opencaesar/oml/issues/27 and https://github.com/opencaesar/oml/pull/28

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

## Sub-task List
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by melaasar** [comment]
This is supported  now as per commit # https://github.com/opencaesar/owl-adapter/commit/568697ccae25a7a8b068ad3394a4a244efe08f93
