### ISSUE TITLE
[BUG] - documentation readme.md build.gradle example

### ISSUE THREAD

**Issue by xdobry** [opencaesar/owl-adapter#26]
## Description
the documentation of gradle usage has some mistakes

## Steps to Reproduce
run the example build.gradle (it is named gradle.buid in README) script from docu on fresh envirorment

You will get following errors

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'example-firesat'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.beust:jcommander:1.72.

```
## Expected Behavior
change **gradle.build** to **build.gradle** in the README.md

add additional central repo 

```
repositories {
		mavenLocal()
		maven { url 'https://dl.bintray.com/opencaesar/owl-adapter' }
		maven { url 'https://dl.bintray.com/opencaesar/oml' }
                jcenter()
	}
```

**Comment by melaasar** [comment]
Thanks for the proposed fixes. I merged them.
