### ISSUE TITLE
How to slove the problem that inputResource.getContents() is null? 

### ISSUE THREAD

**Issue by username123wy** [opencaesar/owl-adapter#39]
## Description
my environment:
JDK version:11.0.8
Gradle version: 6.5.1
The program throws an NullPointerException because the inputResource.getContents() is null. However, the inputResource is not null. 

Exception in thread "main" java.lang.NullPointerException
	at io.opencaesar.oml2owl.Oml2OwlApp.run(Oml2OwlApp.java:164)
	at io.opencaesar.oml2owl.Oml2OwlApp.main(Oml2OwlApp.java:111)
## Additional Context
The input oml folder :E:/input/vocabulary-1.oml . I don't think it's the OML file.

## Relevant screenshots
![image](https://user-images.githubusercontent.com/35055195/101117294-a7162880-3621-11eb-8015-188e827e72f5.png)

**Comment by melaasar** [comment]
Can you please rerun this with the latest revision and let me know if you still get the NPE? If so, please copy here the whole stacktrace. Thanks.

**Comment by melaasar** [comment]
Closing for lack of input. If you still need to follow up on this, please reopen.
